version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_prakerin
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: fauzan25   # ganti sesuai password yang kamu pakai
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_prakerin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      - mysql

volumes:
  db_data:
